language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - 1.11


install:
  - go get github.com/sirupsen/logrus
  - go get github.com/flosch/pongo2
  - go get golang.org/x/net/http2

script: go test -v
